server:
  port: 8006
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka
  instance:
    instance-id: user-consumer8002
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://localhost:7800
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: user-consumer
feign:
  hystrix:
    enabled: false
logging:
  level: info
order-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
